<?php
$name = '[{"appname":""愤怒的小鸟" "哈哈哈" ","appid":"com.PoseidonApp.zoey101.finddifferences","iconURL":"http://imgsdown.1mobile.com/group3/M00/44/C2/S34UR1OG6F2APkgVAAAwU2XBzMc763.png","pkgname":"com.PoseidonApp.zoey101.finddifferences","appimg":"http://imgsdown.1mobile.com/group3/M00/44/C3/S34UR1OG6VaAAx9vAABfo9NQ0z0427.png","comments":""comments1" \'abc\'","attachment_id":"940"},{"appname":"Racinggame","appid":"com.Racinggames.online.AOUTQCTLQAFGMNEIB","iconURL":"http://imgsdown.1mobile.com/group3/M00/44/C2/S34UR1OG6GCATKUWAAA03i3rJN8089.png","pkgname":"com.Racinggames.online.AOUTQCTLQAFGMNEIB","appimg":"http://imgsdown.1mobile.com/group1/M00/1C/EF/S340LlOG6XuAZZYPAACap6aghrk055.png","comments":"","attachment_id":"942"},{"appname":"Zoey 101 Find Differences","appid":"com.PoseidonApp.zoey101.finddifferences","iconURL":"http://imgsdown.1mobile.com/group3/M00/44/C2/S34UR1OG6F2APkgVAAAwU2XBzMc763.png","pkgname":"com.PoseidonApp.zoey101.finddifferences","appimg":"http://imgsdown.1mobile.com/group2/M00/BC/C8/S36rZFOG6kGAEuTZAABZAttWDcE742.png","comments":"","attachment_id":"944"},{"appname":"Preschool Math Booster Zoo","appid":"com.OneMonkClapping.MathBoosterZoo","iconURL":"http://imgsdown.1mobile.com/group3/M00/44/C2/S34UR1OG6FqAY-3zAAAxXZQPYy0740.png","pkgname":"com.OneMonkClapping.MathBoosterZoo","appimg":"http://imgsdown.1mobile.com/group1/M00/1C/EF/S340LlOG6c2AToSvAABZAttWDcE345.png","comments":"","attachment_id":"946"},{"appname":"Seratis","appid":"ch.bullfin.seratis","iconURL":"http://imgsdown.1mobile.com/group2/M00/BC/C7/S36rZFOG6FGAJ7wXAAAWaETjqyo129.png","pkgname":"ch.bullfin.seratis","appimg":"","comments":"","attachment_id":0},{"appname":"FIFA 13 Game Free“hhh哈","appid":"com.wFifa13gamefree","iconURL":"http://imgsdown.1mobile.com/group1/M00/79/E0/S340LlMa-HeAAKT6AAAt_gE7GoQ112.png","pkgname":"com.wFifa13gamefree","appimg":"","comments":"哈哈”ss“l"","attachment_id":0}]';
$name_addslashes = addslashes( $name );
$name_str_replace = str_replace( '\\','\\\\',$name_addslashes );
$name_str_replace_only_double_quote = str_replace( '\\"','\\\\"',$name_addslashes );
echo $name."\n";
echo $name_addslashes."\n";
echo $name_str_replace."\n";
echo '##########################################################################################'."\n";
echo $name_str_replace_only_double_quote."\n";
echo '##########################################################################################'."\n";
exit;
$name_end = '[{\\"appname\\":\\"\\"愤怒的小鸟\\" \\"哈哈哈\\" \\",\\"appid\\":\\"com.PoseidonApp.zoey101.finddifferences\\",\\"iconURL\\":\\"http://imgsdown.1mobile.com/group3/M00/44/C2/S34UR1OG6F2APkgVAAAwU2XBzMc763.png\\",\\"pkgname\\":\\"com.PoseidonApp.zoey101.finddifferences\\",\\"appimg\\":\\"http://imgsdown.1mobile.com/group3/M00/44/C3/S34UR1OG6VaAAx9vAABfo9NQ0z0427.png\\",\\"comments\\":\\"\\"comments1\\" \'abc\'\\",\\"attachment_id\\":\\"940\\"},{\\"appname\\":\\"Racinggame\\",\\"appid\\":\\"com.Racinggames.online.AOUTQCTLQAFGMNEIB\\",\\"iconURL\\":\\"http://imgsdown.1mobile.com/group3/M00/44/C2/S34UR1OG6GCATKUWAAA03i3rJN8089.png\\",\\"pkgname\\":\\"com.Racinggames.online.AOUTQCTLQAFGMNEIB\\",\\"appimg\\":\\"http://imgsdown.1mobile.com/group1/M00/1C/EF/S340LlOG6XuAZZYPAACap6aghrk055.png\\",\\"comments\\":\\"\\",\\"attachment_id\\":\\"942\\"},{\\"appname\\":\\"Zoey 101 Find Differences\\",\\"appid\\":\\"com.PoseidonApp.zoey101.finddifferences\\",\\"iconURL\\":\\"http://imgsdown.1mobile.com/group3/M00/44/C2/S34UR1OG6F2APkgVAAAwU2XBzMc763.png\\",\\"pkgname\\":\\"com.PoseidonApp.zoey101.finddifferences\\",\\"appimg\\":\\"http://imgsdown.1mobile.com/group2/M00/BC/C8/S36rZFOG6kGAEuTZAABZAttWDcE742.png\\",\\"comments\\":\\"\\",\\"attachment_id\\":\\"944\\"},{\\"appname\\":\\"Preschool Math Booster Zoo\\",\\"appid\\":\\"com.OneMonkClapping.MathBoosterZoo\\",\\"iconURL\\":\\"http://imgsdown.1mobile.com/group3/M00/44/C2/S34UR1OG6FqAY-3zAAAxXZQPYy0740.png\\",\\"pkgname\\":\\"com.OneMonkClapping.MathBoosterZoo\\",\\"appimg\\":\\"http://imgsdown.1mobile.com/group1/M00/1C/EF/S340LlOG6c2AToSvAABZAttWDcE345.png\\",\\"comments\\":\\"\\",\\"attachment_id\\":\\"946\\"},{\\"appname\\":\\"Seratis\\",\\"appid\\":\\"ch.bullfin.seratis\\",\\"iconURL\\":\\"http://imgsdown.1mobile.com/group2/M00/BC/C7/S36rZFOG6FGAJ7wXAAAWaETjqyo129.png\\",\\"pkgname\\":\\"ch.bullfin.seratis\\",\\"appimg\\":\\"\\",\\"comments\\":\\"\\",\\"attachment_id\\":0},{\\"appname\\":\\"FIFA 13 Game Free“hhh哈\\",\\"appid\\":\\"com.wFifa13gamefree\\",\\"iconURL\\":\\"http://imgsdown.1mobile.com/group1/M00/79/E0/S340LlMa-HeAAKT6AAAt_gE7GoQ112.png\\",\\"pkgname\\":\\"com.wFifa13gamefree\\",\\"appimg\\":\\"\\",\\"comments\\":\\"哈哈”ss“l\\"\\",\\"attachment_id\\":0}';
$lnk = mysql_connect('localhost', 'jimmychou', 'penny7531')
       or die ('Not connected : ' . mysql_error());

// make foo the current db
mysql_select_db('jimmychou', $lnk) or die ('Can\'t use jimmychou : ' . mysql_error());
mysql_query( "INSERT INTO `jimmychou` SET `name`='".$name_end."'" );
